# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_projecten\ORMit\designer\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.version = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.gridLayout.addWidget(self.version, 3, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1006, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_extractor = QtWidgets.QWidget()
        self.tab_extractor.setObjectName("tab_extractor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_extractor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_extractor)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.frame = QtWidgets.QFrame(self.tab_extractor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_extractor, "")
        self.tab_preferences = QtWidgets.QWidget()
        self.tab_preferences.setObjectName("tab_preferences")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_preferences)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_preferences)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_preferences)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushStyle = QtWidgets.QComboBox(self.groupBox_3)
        self.pushStyle.setObjectName("pushStyle")
        self.verticalLayout.addWidget(self.pushStyle)
        self.pushFont = QtWidgets.QPushButton(self.groupBox_3)
        self.pushFont.setObjectName("pushFont")
        self.verticalLayout.addWidget(self.pushFont)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_preferences)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6.addWidget(self.groupBox_6, 1, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_preferences)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6.addWidget(self.groupBox_5, 0, 3, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_preferences)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_6.addWidget(self.groupBox_7, 1, 2, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_preferences)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6.addWidget(self.groupBox_8, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_preferences, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setEnabled(False)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setEnabled(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCheck_for_updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_updates.setEnabled(False)
        self.actionCheck_for_updates.setObjectName("actionCheck_for_updates")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAbout)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCheck_for_updates)
        self.menuEdit.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ORMit"))
        MainWindow.setToolTip(_translate("MainWindow", "SwitchIt"))
        self.version.setText(_translate("MainWindow", "VersionPlaceholder"))
        self.textBrowser.setToolTip(_translate("MainWindow", "NSP Extractor"))
        self.pushButton.setText(_translate("MainWindow", "COPY RESULTS"))
        self.pushButton_2.setText(_translate("MainWindow", "CONVERT SQL"))
        self.lineEdit.setText(_translate("MainWindow", "PYTHON_VARIABLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_extractor), _translate("MainWindow", "ORMit"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Placeholder"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Style"))
        self.pushFont.setText(_translate("MainWindow", "Font"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Placeholder"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Placeholder"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Placeholder"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Placeholder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preferences), _translate("MainWindow", "Preferences"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Info"))
        self.actionSave.setText(_translate("MainWindow", "Save output..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open SQL..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit app..."))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionAbout.setText(_translate("MainWindow", "About ORMit..."))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionCheck_for_updates.setText(_translate("MainWindow", "Check for updates..."))
        self.actionCheck_for_updates.setShortcut(_translate("MainWindow", "Ctrl+U"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

